theme: jekyll-theme-hacker
timezone: America/Recife
encoding: UTF-8
markdown: kramdown
sass:
  style: compressed
paginate: 3
permalink: pretty

title: Iagows
description: Arduino, circuits, apps and books.
url: https://iagows.github.io/
author:
  name: Iago Alves
  nickname: iagows
  email: el.iagows@gmail.com
  github: iagows
  twitter: iagows