theme: jekyll-theme-hacker
description: Livros, programas e códigos.
markdown: kramdown

title: iasPP
author:
  name: Iago Alves da Silva
  email: el.iagows@gmail.com
  github: iagows
  twitter: iagows