theme: jekyll-theme-hacker
title: Iagows
description: Arduino, circuitos, programas e livros.

markdown: kramdown

author:
  name: Iago Alves
  email: el.iagows@gmail.com
  github: iagows
  twitter: iagows

url: https://iagows.github.io/

plugins: [jekyll-paginate]
paginate: 3